### ISSUE TITLE
Add a Dual Shock 3/4 configuration with flipped Confirm / Cancel buttons.

### ISSUE THREAD

**Issue by marcosandresacevedo** [misteraddons/Mister-Input-Maps#1]
I thought it would be a good idea to include a Dual Shock controllers configuration for those of us that might want to use Japanese style confirm / cancel configurations on the menu with the ◯ for confirm and ✖ for cancel.

**Comment by misteraddons** [comment]
Sorry, only one mapping per controller works because the file names collide. Also, the controller can be easily remapped, this just gets you started.
